all:
	cd pso/src/ && make && make install && cd -
	cd grd/src/ && make && make install && cd -
	cd dsp/src/ && make && make install && cd -

clean:
	cd pso/src/ && make clean && cd -
	cd grd/src/ && make clean && cd -
	cd dsp/src/ && make clean && cd -
